#!/bin/sh -e

if [ $# -eq 0 ];
then
    COMMAND=install
else
    case "$1" in
        install)
            COMMAND=$1
            ;;
        update)
            COMMAND=$1
            ;;
        *)
            echo "Usage: $0 [install|setup]"
            exit 1
            ;;
    esac
fi

if which realpath > /dev/null
then
    # Nothing to do....
    :
elif which grealpath > /dev/null
then
    echo "Using grealpath"
    alias realpath=grealpath
elif which perl > /dev/null
then
    echo "Using perl"
    realpath() {
        perl -e 'use Cwd "abs_path"; print abs_path(@ARGV[0])' -- "$1"
    }
elif which perl > /dev/null
then
    echo "Using php"
    realpath() {
        php -r 'echo realpath($argv[1]),"\n";' -- "$1"
    }
else
    echo "Error: No realpath, grealpath, perl or php."
    echo "Installing 'coreutils' using homebrew or macports should fix this."
    exit 1
fi

PACKAGE_LOCATION=$(realpath $(dirname $(realpath $0))/../..)

echo "Setting up at '$PACKAGE_LOCATION'"
echo "with command '$COMMAND'."
echo
echo Running composer:
echo

cd $PACKAGE_LOCATION/share/daniels-scripts/php
composer $COMMAND

echo
echo Finished
